import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { listAdminCategories, listAdminProducts } from '../services/catalog';
import { getWebsiteAdmin, getWebsiteReview, saveWebsiteCategory, saveWebsiteContent, saveWebsiteReview, saveHomepageProduct } from '../services/website';
import { adminErrorMessage, catalogId } from '../admin/catalog-form';
import '../admin.css';
import '../website-admin.css';

const sections = [['overview', 'Overview'], ['orders', 'Orders'], ['products', 'Products'], ['categories', 'Categories'], ['homepage', 'Homepage'], ['reviews', 'Reviews'], ['content', 'Site content'], ['customers', 'Customers'], ['analytics', 'Analytics'], ['notifications', 'Email delivery'], ['payments', 'Payment settings']];
const money = new Intl.NumberFormat('en-EG', { style: 'currency', currency: 'EGP' });
const date = (value) => value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium' }).format(new Date(value)) : '—';
const errorMessage = (error) => error?.response?.data?.error?.details?.map((item) => item.message).join(' ') || adminErrorMessage(error);
const button = 'admin-button';
const secondary = 'admin-button admin-button-secondary';

function QueryState({ query }) {
  if (query.isPending) return <p className="admin-state" role="status">Loading…</p>;
  if (query.isError) return <div className="admin-state" role="alert"><p>{errorMessage(query.error)}</p><button type="button" className={secondary} onClick={() => query.refetch()}>Try again</button></div>;
  return null;
}
function SaveState({ mutation }) {
  return <>{mutation.isError && <p className="admin-feedback admin-feedback-error" role="alert">{errorMessage(mutation.error)}</p>}{mutation.isSuccess && <p className="admin-feedback" role="status">Changes saved.</p>}</>;
}
function Pagination({ data, page, change }) {
  const pages = Math.max(1, data?.pagination?.pages || 0);
  return <nav className="admin-pagination" aria-label="Admin pagination"><button type="button" className={secondary} disabled={page <= 1} onClick={() => change(page - 1)}>Previous page</button><span>Page {page} of {pages} · {data?.pagination?.total ?? 0} records</span><button type="button" className={secondary} disabled={page >= pages || page >= 200} onClick={() => change(page + 1)}>Next page</button></nav>;
}
function useListFilters() {
  const [params, setParams] = useSearchParams();
  const page = Math.max(1, Math.min(200, Number(params.get('page')) || 1));
  const q = params.get('q') || '';
  const change = (name, value) => { const next = new URLSearchParams(params); if (value) next.set(name, String(value)); else next.delete(name); if (name !== 'page') next.delete('page'); setParams(next); };
  return { params, page, q, change };
}
function SearchForm({ q, label = 'Search', change }) {
  return <form className="admin-search" onSubmit={(event) => { event.preventDefault(); change('q', new FormData(event.currentTarget).get('q').trim()); }}><label>{label}<span className="admin-inline"><input name="q" type="search" key={q} defaultValue={q} maxLength={100} /><button className={secondary} type="submit">Search</button></span></label></form>;
}
function WebsiteOverview() {
  const query = useQuery({ queryKey: ['admin', 'website', 'overview'], queryFn: ({ signal }) => getWebsiteAdmin('overview', undefined, signal), retry: false, staleTime: 60000 });
  const data = query.data;
  const metrics = data ? [
    ['Draft products', data.products.draft, '/admin/products?status=draft'],
    ['Ready products', data.products.ready, '/admin/products?status=ready'],
    ['Products on hold', data.products.hold, '/admin/products?status=hold'],
    ['Customer accounts', data.customers, '/admin/website/customers'],
    ['Orders to prepare', data.pendingOrders, '/admin/commerce/orders'],
    ['Payments to verify', data.awaitingPayment, '/admin/commerce/orders?paymentState=awaiting_verification'],
    ['Reviews in draft', data.draftReviews, '/admin/website/reviews?status=draft'],
    ['Email retries pending', data.notifications?.failed ?? 0, '/admin/website/notifications?state=failed'],
    ['Emails requiring delivery review', data.notifications?.uncertain ?? 0, '/admin/website/notifications?state=uncertain'],
    ['Terminal email failures', data.notifications?.dead ?? 0, '/admin/website/notifications?state=dead'],
  ] : [];
  return <><QueryState query={query} />{data && <><div className="website-metrics">{metrics.map(([label, value, link]) => <Link className="admin-panel website-metric" key={label} to={link}><span>{label}</span><strong>{value}</strong></Link>)}</div><p className="admin-panel">Checkout is {data.checkoutEnabled ? 'enabled by explicit launch configuration' : 'disabled pending launch approval'}. Publishing a product still requires approved prices, inventory and resolved review flags.</p></>}</>;
}
function WebsiteAnalytics() {
  const query = useQuery({ queryKey: ['admin', 'website', 'analytics'], queryFn: ({ signal }) => getWebsiteAdmin('analytics', undefined, signal), retry: false, staleTime: 60000 });
  const data = query.data;
  return <><QueryState query={query} />{data && <section className="admin-panel"><h2>Last 30 days</h2><p>{date(data.since)} – {date(data.until)}. These figures come from saved orders; amounts include shipping. Awaiting transfers are shown separately from collected payments.</p><dl className="website-summary">{[['Orders placed', data.orders], ['Paid orders', data.paidOrders], ['Delivered orders', data.deliveredOrders], ['Cancelled orders', data.cancelledOrders], ['Collected payments', money.format(data.collectedPiastres / 100)], ['Awaiting InstaPay verification', money.format(data.awaitingVerificationPiastres / 100)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>}</>;
}
function WebsiteNotifications() {
  const { page, params, change } = useListFilters();
  const state = params.get('state') || '';
  const query = useQuery({ queryKey: ['admin', 'website', 'notifications', page, state], queryFn: ({ signal }) => getWebsiteAdmin('notifications', { page, limit: 20, ...(state ? { state } : {}) }, signal), retry: false, staleTime: 60000 });
  return <><section className="admin-panel"><h2>Delivery diagnostics</h2><p>Uncertain delivery requires developer review: SMTP may have accepted the message, so automatic retries are suppressed. This screen cannot send or retry emails.</p><label>Delivery state<select value={state} onChange={(event) => change('state', event.target.value)}><option value="">Needs attention</option>{['queued', 'processing', 'failed', 'sent', 'dead', 'uncertain'].map((value) => <option value={value} key={value}>{value}</option>)}</select></label></section><QueryState query={query} />{query.data && <><div className="admin-table-scroll" tabIndex={0} aria-label="Notification delivery table"><table className="admin-products-table"><thead><tr><th>Event</th><th>State</th><th>Attempts</th><th>Created</th><th>Next attempt</th><th>Diagnostic</th></tr></thead><tbody>{query.data.events.map((event) => <tr key={event._id}><td>{event.event.replaceAll('_', ' ')}</td><td>{event.state}</td><td>{event.attempts}</td><td>{date(event.createdAt)}</td><td>{['queued', 'failed'].includes(event.state) ? date(event.nextAttemptAt) : '—'}</td><td>{event.lastErrorCode || '—'}</td></tr>)}</tbody></table>{query.data.events.length === 0 && <p className="admin-state">No notification events in this view.</p>}</div><Pagination data={query.data} page={page} change={(value) => change('page', value)} /></>}</>;
}
function WebsiteCustomers() {
  const { page, q, change } = useListFilters();
  const query = useQuery({ queryKey: ['admin', 'website', 'customers', page, q], queryFn: ({ signal }) => getWebsiteAdmin('customers', { page, limit: 20, ...(q ? { q } : {}) }, signal), retry: false });
  return <><section className="admin-panel"><SearchForm q={q} change={change} label="Exact email or name prefix (case sensitive)" /><p>Customer accounts only. Guest orders remain separate; an unverified contact detail never links orders to an account.</p></section><QueryState query={query} />{query.data && <><div className="admin-table-scroll" tabIndex={0} aria-label="Customer accounts table"><table className="admin-products-table"><thead><tr><th>Name</th><th>Email</th><th>Account</th><th>Joined</th></tr></thead><tbody>{query.data.customers.map((customer) => <tr key={customer._id}><td>{customer.name}</td><td>{customer.email}</td><td>{customer.active ? 'Active' : 'Inactive'}</td><td>{date(customer.createdAt)}</td></tr>)}</tbody></table>{query.data.customers.length === 0 && <p className="admin-state">No matching customer accounts.</p>}</div><Pagination data={query.data} page={page} change={(value) => change('page', value)} /></>}</>;
}
function ProductPicker({ value, onChange, optional = false }) {
  const [search, setSearch] = useState('');
  const [draftSearch, setDraftSearch] = useState('');
  const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ['admin', 'website', 'product-choices', search, page], queryFn: ({ signal }) => listAdminProducts({ q: search || undefined, page, limit: 20, sort: 'name_asc' }, signal), retry: false });
  const find = () => { setSearch(draftSearch.trim()); setPage(1); };
  return <fieldset className="website-fieldset"><legend>Related product{optional ? ' (optional)' : ''}</legend><label>Find a product<span className="admin-inline"><input type="search" maxLength={100} value={draftSearch} onChange={(event) => setDraftSearch(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); find(); } }} /><button className={secondary} type="button" onClick={find}>Find product</button></span></label><label>Select product<select value={value || ''} onChange={(event) => onChange(event.target.value)}><option value="">{optional ? 'General website review' : 'Choose a product'}</option>{value && !(query.data?.products || []).some((product) => catalogId(product) === value) && <option value={value}>Current selection ({value})</option>}{(query.data?.products || []).map((product) => <option value={catalogId(product)} key={catalogId(product)}>{product.name} · {product.status}</option>)}</select></label><QueryState query={query} />{query.data && <Pagination data={query.data} page={page} change={setPage} />}</fieldset>;
}
function ReviewForm({ initial, saved, cancel }) {
  const [form, setForm] = useState(initial || { authorLabel: '', rating: 5, text: '', productId: null, status: 'draft', approved: false, consentConfirmed: false, sourceNote: '', featured: false, displayOrder: 0 });
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value, ...(['authorLabel', 'rating', 'text', 'productId', 'consentConfirmed', 'sourceNote'].includes(key) ? { approved: false, ...(current.status === 'published' ? { status: 'draft' } : {}) } : {}) }));
  const mutation = useMutation({ mutationFn: () => saveWebsiteReview(initial?._id, Object.fromEntries(['authorLabel', 'rating', 'text', 'productId', 'status', 'approved', 'consentConfirmed', 'sourceNote', 'featured', 'displayOrder'].map((key) => [key, form[key]]))), onSuccess: saved });
  return <section className="admin-panel"><h2>{initial ? 'Edit review' : 'Add an owner-approved review'}</h2><p>Enter an authentic quotation and keep its source note private. Customers cannot submit reviews.</p><form className="website-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><label>Display author name<input required maxLength={100} value={form.authorLabel} onChange={(event) => update('authorLabel', event.target.value)} /></label><label>Rating<select value={form.rating} onChange={(event) => update('rating', Number(event.target.value))}>{[1, 2, 3, 4, 5].map((rating) => <option key={rating}>{rating}</option>)}</select></label><label>Review text<textarea required maxLength={3000} rows={5} value={form.text} onChange={(event) => update('text', event.target.value)} /></label><ProductPicker value={form.productId} onChange={(value) => update('productId', value || null)} optional /><label>Private source/provenance note<textarea rows={3} maxLength={2000} value={form.sourceNote} onChange={(event) => update('sourceNote', event.target.value)} /></label><label>Publication<select value={form.status} onChange={(event) => update('status', event.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="hidden">Hidden</option></select></label><label>Homepage display order<input type="number" min={0} max={100000} required value={form.displayOrder} onChange={(event) => update('displayOrder', Number(event.target.value))} /></label><label className="admin-checkbox"><input type="checkbox" checked={form.consentConfirmed} onChange={(event) => update('consentConfirmed', event.target.checked)} />Permission to display this authentic quotation is confirmed</label><label className="admin-checkbox"><input type="checkbox" checked={form.approved} onChange={(event) => update('approved', event.target.checked)} />Owner approval confirmed</label><label className="admin-checkbox"><input type="checkbox" checked={form.featured} onChange={(event) => update('featured', event.target.checked)} />Feature on homepage when published</label><SaveState mutation={mutation} /><div className="admin-inline"><button className={button} disabled={mutation.isPending} type="submit">{mutation.isPending ? 'Saving…' : 'Save review'}</button><button className={secondary} type="button" onClick={cancel}>Close editor</button></div></form></section>;
}
function WebsiteReviews() {
  const { page, q, params, change } = useListFilters();
  const status = params.get('status') || '';
  const [editor, setEditor] = useState(null);
  const client = useQueryClient();
  const query = useQuery({ queryKey: ['admin', 'website', 'reviews', page, q, status], queryFn: ({ signal }) => getWebsiteAdmin('reviews', { page, limit: 20, ...(q ? { q } : {}), ...(status ? { status } : {}) }, signal), retry: false });
  const detail = useQuery({ queryKey: ['admin', 'website', 'review', editor], queryFn: ({ signal }) => getWebsiteReview(editor, signal), enabled: Boolean(editor && editor !== 'new'), retry: false });
  const refresh = () => { client.invalidateQueries({ queryKey: ['admin', 'website'] }); client.invalidateQueries({ queryKey: ['website', 'content'] }); setEditor(null); };
  const hide = useMutation({ mutationFn: (id) => saveWebsiteReview(id, { status: 'hidden' }), onSuccess: refresh });
  return <><section className="admin-panel"><div className="admin-inline"><SearchForm q={q} change={change} label="Search reviews" /><label>Publication<select value={status} onChange={(event) => change('status', event.target.value)}><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="hidden">Hidden</option></select></label><button className={button} onClick={() => setEditor('new')}>Add review</button></div><SaveState mutation={hide} /></section>{editor === 'new' && <ReviewForm saved={refresh} cancel={() => setEditor(null)} />}{editor && editor !== 'new' && <><QueryState query={detail} />{detail.data && <ReviewForm key={editor} initial={detail.data.review} saved={refresh} cancel={() => setEditor(null)} />}</>}<QueryState query={query} />{query.data && <><div className="admin-table-scroll" tabIndex={0} aria-label="Reviews table"><table className="admin-products-table"><thead><tr><th>Author</th><th>Product</th><th>Rating</th><th>Publication</th><th>Homepage</th><th>Actions</th></tr></thead><tbody>{query.data.reviews.map((review) => <tr key={review._id}><td>{review.authorLabel}</td><td>{review.productId?.name || 'General website review'}</td><td>{review.rating}/5</td><td>{review.status} · {review.approved ? 'Approved' : 'Needs approval'}</td><td>{review.featured ? `Selected (${review.displayOrder})` : 'Not selected'}</td><td><div className="admin-inline"><button className={secondary} onClick={() => setEditor(review._id)}>Edit</button><button className={secondary} disabled={hide.isPending || review.status === 'hidden'} onClick={() => hide.mutate(review._id)}>Hide</button></div></td></tr>)}</tbody></table>{query.data.reviews.length === 0 && <p className="admin-state">No reviews yet. Add only authentic, owner-approved quotations.</p>}</div><Pagination data={query.data} page={page} change={(value) => change('page', value)} /></>}</>;
}
const contentSections = [['about', 'About Us'], ['contact', 'Contact'], ['privacyPolicy', 'Privacy Policy'], ['refundPolicy', 'Refund Policy'], ['shippingPolicy', 'Shipping Policy'], ['termsOfService', 'Terms of Service'], ['faq', 'FAQ']];
function ContentEditor({ content, section }) {
  const client = useQueryClient();
  const [form, setForm] = useState(section === 'faq' ? { items: content.faq || [], approved: Boolean(content.faqApproved) } : { ...(content[section] || {}), approved: Boolean(content[section]?.approved) });
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value, ...(key === 'approved' ? {} : { approved: false }) }));
  const mutation = useMutation({ mutationFn: () => saveWebsiteContent(section === 'faq' ? { faq: form.items, faqApproved: form.approved } : { [section]: Object.fromEntries(Object.entries(form).filter(([key]) => key !== 'updatedAt')) }), onSuccess: () => { client.invalidateQueries({ queryKey: ['admin', 'website', 'content'] }); client.invalidateQueries({ queryKey: ['website', 'content'] }); } });
  const editFaq = (index, key, value) => update('items', form.items.map((item, position) => position === index ? { ...item, [key]: value } : item));
  return <form className="website-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}>{section === 'contact' ? <>{[['email', 'Email', 'email'], ['phone', 'Egyptian mobile number', 'tel'], ['whatsapp', 'WhatsApp Egyptian mobile number', 'tel'], ['instagram', 'Instagram HTTPS profile', 'url'], ['address', 'Owner-approved address', 'text']].map(([key, label, type]) => <label key={key}>{label}<input type={type} value={form[key] || ''} maxLength={key === 'address' ? 1000 : key === 'instagram' ? 300 : 254} onChange={(event) => update(key, event.target.value)} /></label>)}<label>Contact introduction<textarea rows={4} maxLength={3000} value={form.body || ''} onChange={(event) => update('body', event.target.value)} /></label></> : section === 'faq' ? <>{form.items.map((item, index) => <fieldset className="website-fieldset" key={index}><legend>Question {index + 1}</legend><label>Question<input required maxLength={250} value={item.question} onChange={(event) => editFaq(index, 'question', event.target.value)} /></label><label>Answer<textarea required rows={3} maxLength={3000} value={item.answer} onChange={(event) => editFaq(index, 'answer', event.target.value)} /></label><button className={secondary} type="button" onClick={() => update('items', form.items.filter((_, position) => position !== index))}>Remove question {index + 1}</button></fieldset>)}<button className={secondary} type="button" disabled={form.items.length >= 20} onClick={() => update('items', [...form.items, { question: '', answer: '' }])}>Add FAQ question</button></> : <><label>Page title<input required maxLength={160} value={form.title || ''} onChange={(event) => update('title', event.target.value)} /></label><label>Owner-approved page text<textarea required rows={12} maxLength={15000} value={form.body || ''} onChange={(event) => update('body', event.target.value)} /></label></>}<label className="admin-checkbox"><input type="checkbox" checked={form.approved} onChange={(event) => update('approved', event.target.checked)} />Owner approval confirmed; make this section public</label><p>Changing content clears approval. Enter reviewed business information and policy text; nothing is published automatically.</p><SaveState mutation={mutation} /><button type="submit" className={button} disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : 'Save section'}</button></form>;
}
function WebsiteContent() {
  const [section, setSection] = useState('about');
  const query = useQuery({ queryKey: ['admin', 'website', 'content'], queryFn: ({ signal }) => getWebsiteAdmin('content', undefined, signal), retry: false });
  return <section className="admin-panel"><h2>Owner-approved website content</h2><label>Section<select value={section} onChange={(event) => setSection(event.target.value)}>{contentSections.map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><QueryState query={query} />{query.data && <ContentEditor key={`${section}:${query.data.content.__v ?? 'new'}`} content={query.data.content} section={section} />}</section>;
}

function CategoryEditor({ initial, roots, done }) {
  const [form, setForm] = useState({ name: '', slug: '', parentId: null, imageKey: null, active: true, featured: false, order: 0, ...initial });
  const mutation = useMutation({ mutationFn: () => saveWebsiteCategory(initial?._id, Object.fromEntries(['name', 'slug', 'parentId', 'imageKey', 'active', 'order', ...(!form.parentId ? ['featured'] : [])].map((key) => [key, form[key]]))), onSuccess: done });
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <section className="admin-panel"><h2>{initial ? 'Edit category' : 'Add category'}</h2><form className="website-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><label>Name<input required maxLength={160} value={form.name} onChange={(event) => update('name', event.target.value)} /></label><label>Unique slug<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={240} value={form.slug} onChange={(event) => update('slug', event.target.value)} /></label><label>Main category<select value={form.parentId || ''} onChange={(event) => update('parentId', event.target.value || null)}><option value="">This is a main category</option>{roots.filter((root) => root._id !== initial?._id).map((root) => <option key={root._id} value={root._id}>{root.name}</option>)}</select></label><label>Existing relative image reference<input maxLength={500} value={form.imageKey || ''} onChange={(event) => update('imageKey', event.target.value || null)} /></label><label>Display order<input type="number" min={0} required value={form.order} onChange={(event) => update('order', Number(event.target.value))} /></label><label className="admin-checkbox"><input type="checkbox" checked={form.active} onChange={(event) => update('active', event.target.checked)} />Active</label><label className="admin-checkbox"><input type="checkbox" checked={form.featured} disabled={Boolean(form.parentId)} onChange={(event) => update('featured', event.target.checked)} />Featured on homepage (main categories only)</label>{form.parentId && <p>Subcategories remain linked from their main category. Homepage selection applies to main categories; any existing subcategory feature metadata is preserved.</p>}<p>Catalog relationships and audited names are preserved unless explicitly edited. A category already used by products or subcategories cannot change its parent.</p><SaveState mutation={mutation} /><div className="admin-inline"><button className={button} disabled={mutation.isPending}>Save category</button><button className={secondary} type="button" onClick={() => done(false)}>Close editor</button></div></form></section>;
}
function WebsiteCategories() {
  const { page, params, change } = useListFilters();
  const parent = params.get('parent') || 'root';
  const active = params.get('active') || '';
  const [editor, setEditor] = useState(null);
  const client = useQueryClient();
  const roots = useQuery({ queryKey: ['admin', 'website', 'category-roots'], queryFn: ({ signal }) => listAdminCategories({ parent: 'root', page: 1, limit: 20 }, signal), retry: false });
  const query = useQuery({ queryKey: ['admin', 'website', 'categories', parent, active, page], queryFn: ({ signal }) => listAdminCategories({ parent, page, limit: 20, ...(active ? { active } : {}) }, signal), retry: false });
  const done = () => { setEditor(null); client.invalidateQueries({ queryKey: ['admin', 'website'] }); client.invalidateQueries({ queryKey: ['categories'] }); };
  return <><section className="admin-panel"><div className="admin-inline"><label>Category group<select value={parent} onChange={(event) => change('parent', event.target.value)}><option value="root">Main categories</option>{(roots.data?.categories || []).map((category) => <option key={category._id} value={category.slug}>{category.name} subcategories</option>)}</select></label><label>Activity<select value={active} onChange={(event) => change('active', event.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></label><button className={button} onClick={() => setEditor('new')}>Add category</button></div><QueryState query={roots} /></section>{editor && <CategoryEditor key={editor === 'new' ? 'new' : editor._id} initial={editor === 'new' ? null : editor} roots={roots.data?.categories || []} done={done} />}<QueryState query={query} />{query.data && <><div className="admin-table-scroll" tabIndex={0} aria-label="Category management table"><table className="admin-products-table"><thead><tr><th>Category</th><th>Products</th><th>Status</th><th>Homepage</th><th>Order</th><th>Actions</th></tr></thead><tbody>{query.data.categories.map((category) => <tr key={category._id}><td><strong>{category.name}</strong><span className="admin-cell-note">{category.slug}</span></td><td>{category.productCount}</td><td>{category.active ? 'Active' : 'Inactive'}</td><td>{category.featured ? 'Featured' : 'Not featured'}</td><td>{category.order}</td><td><button className={secondary} onClick={() => setEditor(category)}>Edit</button></td></tr>)}</tbody></table>{query.data.categories.length === 0 && <p className="admin-state">No categories in this group.</p>}</div><Pagination data={query.data} page={page} change={(value) => change('page', value)} /></>}</>;
}
function WebsiteHomepage() {
  const { page, change } = useListFilters();
  const client = useQueryClient();
  const products = useQuery({ queryKey: ['admin', 'website', 'homepage-products', page], queryFn: ({ signal }) => listAdminProducts({ bestSeller: 'true', sort: 'best_sellers', page, limit: 20 }, signal), retry: false });
  const categories = useQuery({ queryKey: ['admin', 'website', 'homepage-categories'], queryFn: ({ signal }) => listAdminCategories({ parent: 'root', featured: 'true', page: 1, limit: 20 }, signal), retry: false });
  const remove = useMutation({ mutationFn: (id) => saveHomepageProduct(id, { bestSeller: false }), onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'website', 'homepage-products'] }) });
  return <><section className="admin-panel"><h2>Homepage selections</h2><p>Select eight eligible Best Sellers in product management and set their display order. Rankings are administrator selections; no sales statistics are inferred. Public sections exclude draft, unapproved, unavailable or inactive-category products.</p><div className="admin-inline"><Link className={button} to="/admin/products">Choose products</Link><Link className={secondary} to="/admin/website/categories">Manage featured categories</Link><Link className={secondary} to="/admin/website/reviews">Manage featured reviews</Link><Link className={secondary} to="/admin/commerce/bundles">Manage published bundles</Link></div><p>Hero footage and trust figures remain developer-managed and require approved assets or information.</p></section><QueryState query={products} />{products.data && <section className="admin-panel"><h2>Best Seller selections ({products.data.pagination.total})</h2>{products.data.pagination.total !== 8 && <p role="status">The storefront displays the complete eight-product section only when eight eligible selections are configured.</p>}<SaveState mutation={remove} /><div className="website-selection-list">{products.data.products.map((product) => <div key={product._id}><strong>{product.name}</strong><span>{product.status} · {product.priceApproved && product.inventory?.approved && !product.reviewRequired ? 'Approvals complete' : 'Requires merchant review'} · Order {product.bestSellerOrder}</span><div className="admin-inline"><Link to={`/admin/products/${product._id}/edit`}>Edit selection</Link><button className={secondary} disabled={remove.isPending} onClick={() => remove.mutate(product._id)}>Remove selection</button></div></div>)}</div><Pagination data={products.data} page={page} change={(value) => change('page', value)} /></section>}<QueryState query={categories} />{categories.data && <section className="admin-panel"><h2>Featured categories</h2>{categories.data.categories.length ? <ul>{categories.data.categories.map((category) => <li key={category._id}>{category.name} · {category.active ? 'Active' : 'Inactive'} · Order {category.order}</li>)}</ul> : <p>No featured categories configured.</p>}</section>}</>;
}
function WebsitePayments() {
  const query = useQuery({ queryKey: ['admin', 'website', 'payment-settings'], queryFn: ({ signal }) => getWebsiteAdmin('payment-settings', undefined, signal), retry: false });
  return <><QueryState query={query} />{query.data && <section className="admin-panel"><h2>Payment and launch controls</h2><p>Checkout is {query.data.checkoutEnabled ? 'enabled by the authorized environment configuration' : 'disabled pending launch approval'}. Launch flags are environment-managed and cannot be changed from this dashboard.</p>{query.data.methods.map((method) => <div key={method.key}><h3>{method.name}</h3>{method.transferNumber && <p>Full-payment transfer number: {method.transferNumber}</p>}<p>{method.verification}</p></div>)}<Link className={secondary} to="/admin/commerce/shipping">Manage approved shipping rates</Link><p>Proof images are opened only by an authorized administrator explicitly selecting View Proof on an order.</p></section>}</>;
}

export default function AdminWebsitePage() {
  const { section = 'overview' } = useParams();
  const component = { overview: WebsiteOverview, analytics: WebsiteAnalytics, customers: WebsiteCustomers, reviews: WebsiteReviews, content: WebsiteContent, categories: WebsiteCategories, homepage: WebsiteHomepage, payments: WebsitePayments, notifications: WebsiteNotifications }[section];
  const Component = component;
  const title = sections.find(([key]) => key === section)?.[1] || 'Page unavailable';
  return <main className="admin-shell website-admin"><div className="admin-page-heading"><div><p className="admin-eyebrow">Tap & Wrap administration</p><h1>{title}</h1></div><Link className={secondary} to="/">View storefront</Link></div><nav className="website-admin-nav" aria-label="Administration">{sections.map(([key, label]) => <Link key={key} aria-current={key === section ? 'page' : undefined} to={key === 'orders' ? '/admin/commerce/orders' : key === 'products' ? '/admin/products' : `/admin/website/${key}`}>{label}</Link>)}<Link to="/admin/commerce/templates">Customization</Link><Link to="/admin/commerce/components">Components</Link><Link to="/admin/commerce/bundles">Bundles</Link><Link to="/admin/commerce/discounts">Discounts</Link><Link to="/admin/commerce/shipping">Shipping</Link></nav>{Component ? <Component /> : <section className="admin-panel"><p>This administration section is not available.</p><Link to="/admin/website/overview">Return to overview</Link></section>}</main>;
}
