import { useEffect, useId, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../services/api';
import { adminCommerceGet } from './api';
import { decimalInput, parseDecimalPiastres } from './money-input';
import { cairoDateTimeInput, cairoDateTimeCandidates, resolveCairoDateTime } from '../admin/cairo-time.js';
import { FieldError, fieldErrorProps } from '../components/FormFeedback.jsx';

export function BusinessDateTimeField({ label, name, value, onChange }) {
  const id = useId();
  const input = useRef(null);
  const [draft, setDraft] = useState(() => cairoDateTimeInput(value));
  const [occurrence, setOccurrence] = useState('');
  const [error, setError] = useState('');
  let candidates = [];
  try { candidates = cairoDateTimeCandidates(draft); } catch { /* The editable draft is explained below, never normalized silently. */ }
  useEffect(() => {
    const next = cairoDateTimeInput(value);
    setDraft(next);
    let times = [];
    try { times = cairoDateTimeCandidates(next); } catch { /* Invalid stored dates must be corrected explicitly. */ }
    setOccurrence(times.length > 1 ? (Math.floor(Date.parse(times[1]) / 60000) === Math.floor(Date.parse(value) / 60000) ? 'second' : 'first') : '');
    setError('');
  }, [value]);
  useEffect(() => { input.current?.setCustomValidity(error); }, [error]);
  function change(next, choice = '') {
    setDraft(next); setOccurrence(choice);
    try { const iso = resolveCairoDateTime(next, choice); setError(''); onChange(iso); }
    catch (failure) { setError(failure.message); }
  }
  return <div className="commerce-field"><label htmlFor={id}>{label} (Cairo time)</label><input id={id} name={name} ref={input} type="datetime-local" step="60" value={draft} onChange={event => change(event.target.value)} {...fieldErrorProps(id, error, `${id}-help`)} /><small id={`${id}-help`}>Africa/Cairo, including daylight saving. Stored as an exact UTC instant.</small>{candidates.length > 1 && <label>Clock-change occurrence<select aria-label={`${label} clock-change occurrence`} value={occurrence} onChange={event => change(draft, event.target.value)}><option value="">Choose occurrence</option><option value="first">First occurrence (before clocks move back)</option><option value="second">Second occurrence (after clocks move back)</option></select></label>}<FieldError id={id}>{error}</FieldError></div>;
}

export function TextField({ label, value, onChange, type = 'text', required = false, ...rest }) {
  return <label className="commerce-field">{label}<input type={type} value={value ?? ''} onChange={(event) => onChange(type === 'number' ? (event.target.value === '' ? null : Number(event.target.value)) : event.target.value)} required={required} {...rest} /></label>;
}
export function MoneyField({ label, name, value, onChange, required = false, allowNegative = false, unit = 'EGP', maximum = 100000000, minimum = allowNegative ? -maximum : 0 }) {
  const [draft, setDraft] = useState(() => decimalInput(value));
  const input = useRef(null);
  useEffect(() => {
    setDraft((previous) => {
      try { if (parseDecimalPiastres(previous, { allowNegative, maximum, minimum }) === value) return previous; } catch { /* A deliberate external value change replaces an invalid draft. */ }
      input.current?.setCustomValidity('');
      return decimalInput(value);
    });
  }, [value, allowNegative, maximum, minimum]);
  return <label className="commerce-field">{label}{unit && ` (${unit})`}<input name={name} ref={input} type="text" inputMode="decimal" required={required} value={draft} onChange={(event) => {
    setDraft(event.target.value);
    try {
      const next = parseDecimalPiastres(event.target.value, { allowNegative, maximum, minimum });
      event.target.setCustomValidity('');
      onChange(next);
    } catch (error) { event.target.setCustomValidity(error.message); }
  }} /></label>;
}
export function CheckField({ label, name, value, onChange }) {
  return <label className="commerce-field"><span><input name={name} type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} /> {label}</span></label>;
}
export function SelectField({ label, name, value, onChange, options, required = false }) {
  return <label className="commerce-field">{label}<select name={name} value={value ?? ''} required={required} onChange={(event) => onChange(event.target.value)}>{options.map((entry) => <option value={typeof entry === 'string' ? entry : entry.value} key={typeof entry === 'string' ? entry : entry.value}>{typeof entry === 'string' ? entry.replaceAll('_', ' ') : entry.label}</option>)}</select></label>;
}

export function ProductPicker({ value, name, onChange, label = 'Product', allowEmpty = false }) {
  const [search, setSearch] = useState('');
  const [submitted, setSubmitted] = useState('');
  const query = useQuery({ queryKey: ['admin', 'commerce', 'product-picker', submitted], queryFn: async ({ signal }) => (await api.get('/admin/products', { params: { q: submitted || undefined, limit: 20, page: 1 }, signal })).data.data, retry: false, staleTime: 60_000 });
  const products = query.data?.products || [];
  return <div className="commerce-editor-row"><label className="commerce-field">Find {label.toLowerCase()}<input value={search} onChange={(event) => setSearch(event.target.value)} /></label><button className="button button-secondary" type="button" onClick={() => setSubmitted(search.trim())}>Find products</button><label className="commerce-field">{label}<select name={name} value={value || ''} required={!allowEmpty} onChange={(event) => onChange(event.target.value)}><option value="">Select product</option>{value && !products.some((product) => (product._id || product.id) === value) && <option value={value}>Selected product ({value})</option>}{products.map((product) => <option key={product._id || product.id} value={product._id || product.id}>{product.name}</option>)}</select></label>{query.isFetching && <small role="status">Loading up to 20 products…</small>}</div>;
}
function ComponentPicker({ value, name, onChange }) {
  const [search, setSearch] = useState('');
  const [submitted, setSubmitted] = useState('');
  const query = useQuery({ queryKey: ['admin', 'commerce', 'component-picker', submitted], queryFn: ({ signal }) => adminCommerceGet('/components', { search: submitted || undefined, limit: 20, page: 1 }, signal), retry: false, staleTime: 60_000 });
  const components = query.data?.components || [];
  return <div><div className="commerce-inline-form"><label className="commerce-field">Find component<input value={search} onChange={(event) => setSearch(event.target.value)} /></label><button type="button" className="button button-secondary" onClick={() => setSubmitted(search.trim())}>Find</button></div><label className="commerce-field">Component (optional)<select name={name} value={value || ''} onChange={(event) => onChange(event.target.value || null)}><option value="">No component — adjustment only</option>{value && !components.some((component) => (component._id || component.id) === value) && <option value={value}>Selected component ({value})</option>}{components.map((component) => <option key={component._id || component.id} value={component._id || component.id}>{component.name}</option>)}</select></label></div>;
}

export function CategoryPicker({ value, name, onChange, parent = 'root', label = 'Main category', required = true }) {
  const [search, setSearch] = useState('');
  const [submitted, setSubmitted] = useState('');
  const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ['admin', 'commerce', 'category-picker', parent, submitted, page], queryFn: async ({ signal }) => (await api.get('/admin/categories', { params: { parent, search: submitted || undefined, limit: 20, page, includeProductCounts: false }, signal })).data.data, enabled: Boolean(parent), retry: false, staleTime: 60_000 });
  const categories = query.data?.categories || [];
  return <div className="commerce-editor-row"><div className="commerce-inline-form"><label className="commerce-field">Find {label.toLowerCase()}<input value={search} maxLength={100} onChange={(event) => setSearch(event.target.value)} disabled={!parent} /></label><button type="button" className="button button-secondary" disabled={!parent} onClick={() => { setSubmitted(search.trim()); setPage(1); }}>Find categories</button></div><label className="commerce-field">{label}<select name={name} value={value || ''} disabled={!parent || query.isPending || query.isError} required={required} onChange={(event) => onChange(event.target.value || null, categories.find((category) => category._id === event.target.value))}><option value="">Select category</option>{value && !categories.some((category) => category._id === value) && <option value={value}>Current selected category</option>}{categories.map((category) => <option key={category._id} value={category._id}>{category.name}{category.active ? '' : ' (inactive)'}</option>)}</select></label>{query.isFetching && <small role="status">Loading categories…</small>}{query.error && <p className="form-error" role="alert">Categories could not be loaded. <button type="button" onClick={() => query.refetch()}>Try again</button></p>}<nav className="commerce-pagination" aria-label={`${label} pages`}><button type="button" disabled={page <= 1 || query.isFetching} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page}</span><button type="button" disabled={query.isFetching || page >= (query.data?.pagination?.pages || query.data?.pagination?.totalPages || 1)} onClick={() => setPage(page + 1)}>Next</button></nav></div>;
}

export function FieldDefinitions({ fields, onChange, product = false }) {
  const update = (index, key, value) => onChange(fields.map((field, position) => position === index ? { ...field, [key]: value } : field));
  return <section><h3>{product ? 'Purchase Requirements' : 'Personalization Fields'}</h3>{fields.map((field, index) => <div className="commerce-editor-row" key={index}><div className="commerce-editor-grid"><TextField name={`${product ? 'personalization.fields' : 'fields'}.${index}.key`} label="Field key" value={field.key} onChange={(value) => update(index, 'key', value)} required maxLength={product ? 50 : 64} pattern={product ? "[a-z][a-z0-9_-]{0,49}" : "[a-z][a-z0-9_-]{0,63}"} /><TextField name={`${product ? 'personalization.fields' : 'fields'}.${index}.label`} label="Customer-facing label" maxLength={120} value={field.label} onChange={(value) => update(index, 'label', value)} required /><SelectField name={`${product ? 'personalization.fields' : 'fields'}.${index}.type`} label="Field type" value={field.type} onChange={(value) => update(index, 'type', value)} options={product ? ['short_text', 'long_text', 'select', 'image'] : ['text', 'textarea', 'image']} /><CheckField name={`${product ? 'personalization.fields' : 'fields'}.${index}.required`} label="Required" value={field.required} onChange={(value) => update(index, 'required', value)} /></div>
    {field.type === 'image' ? <><div className="commerce-editor-grid"><TextField name={`${product ? 'personalization.fields' : 'fields'}.${index}.minFiles`} label="Minimum files" type="number" min="0" max="10" value={field.minFiles} onChange={(value) => update(index, 'minFiles', value)} /><TextField name={`${product ? 'personalization.fields' : 'fields'}.${index}.maxFiles`} label="Maximum files" type="number" min="1" max="10" value={field.maxFiles} onChange={(value) => update(index, 'maxFiles', value)} /><TextField name={`${product ? 'personalization.fields' : 'fields'}.${index}.maxBytes`} label="Maximum size per file (bytes; 1048576 = 1 MB)" type="number" min="1" max="10485760" value={field.maxBytes ?? 8 * 1024 * 1024} onChange={(value) => update(index, 'maxBytes', value)} /></div><fieldset className="commerce-option-group" name={`${product ? 'personalization.fields' : 'fields'}.${index}.acceptedMimeTypes`} tabIndex={-1}><legend>Accepted formats</legend>{['image/jpeg', 'image/png', 'image/webp'].map((mime) => <CheckField key={mime} label={mime.replace('image/', '').toUpperCase()} value={(field.acceptedMimeTypes || []).includes(mime)} onChange={(checked) => update(index, 'acceptedMimeTypes', checked ? [...(field.acceptedMimeTypes || []), mime] : (field.acceptedMimeTypes || []).filter((value) => value !== mime))} />)}</fieldset></> : <><TextField name={`${product ? 'personalization.fields' : 'fields'}.${index}.${product ? 'maxLength' : 'maxChars'}`} label="Character limit" type="number" min="1" max={product ? 5000 : 2000} value={field[product ? 'maxLength' : 'maxChars']} onChange={(value) => update(index, product ? 'maxLength' : 'maxChars', value)} />{field.type === 'select' && <label className="commerce-field">Choices (one per line)<textarea name={`personalization.fields.${index}.choices`} value={(field.choices || []).join('\n')} onChange={(event) => update(index, 'choices', event.target.value.split('\n').filter(Boolean))} rows={4} /></label>}</>}
    <button className="commerce-link-button" type="button" onClick={() => onChange(fields.filter((_, position) => position !== index))}>Remove field {index + 1}</button></div>)}<button className="button button-secondary" type="button" onClick={() => onChange([...fields, { key: '', label: '', type: product ? 'short_text' : 'text', required: false, [product ? 'maxLength' : 'maxChars']: 120, minFiles: 0, maxFiles: 1, maxBytes: 8 * 1024 * 1024, acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'] }])}>Add requirement field</button></section>;
}

function EngravingOptions({ name, options, onChange }) {
  const change = (index, key, value) => onChange(options.map((option, position) => position === index ? { ...option, [key]: value } : option));
  return <section><h3>{name}</h3>{options.map((option, index) => <div key={index} className="commerce-editor-row"><div className="commerce-editor-grid"><TextField name={`engraving.${name.toLowerCase()}.${index}.key`} label="Option key" maxLength={64} pattern="[a-z][a-z0-9_-]{0,63}" value={option.key} onChange={(value) => change(index, 'key', value)} required /><TextField name={`engraving.${name.toLowerCase()}.${index}.label`} label="Label" maxLength={120} value={option.label} onChange={(value) => change(index, 'label', value)} required /><MoneyField name={`engraving.${name.toLowerCase()}.${index}.adjustmentPiastres`} label="Price adjustment" value={option.adjustmentPiastres} onChange={(value) => change(index, 'adjustmentPiastres', value)} /><CheckField name={`engraving.${name.toLowerCase()}.${index}.active`} label="Available" value={option.active} onChange={(value) => change(index, 'active', value)} /></div><button className="commerce-link-button" type="button" onClick={() => onChange(options.filter((_, position) => position !== index))}>Remove option</button></div>)}<button className="button button-secondary" type="button" onClick={() => onChange([...options, { key: '', label: '', active: true, adjustmentPiastres: 0 }])}>Add {name.toLowerCase()} option</button></section>;
}

export function TemplateEditor({ value, onChange }) {
  const set = (key, next) => onChange({ ...value, [key]: next });
  const changeGroup = (index, key, next) => set('groups', value.groups.map((group, position) => position === index ? { ...group, [key]: next } : group));
  const changeOption = (groupIndex, optionIndex, key, next) => changeGroup(groupIndex, 'options', value.groups[groupIndex].options.map((option, position) => position === optionIndex ? { ...option, [key]: next } : option));
  const engraving = value.engraving || {};
  const setEngraving = (key, next) => set('engraving', { ...engraving, [key]: next });
  return <><div className="commerce-editor-grid"><TextField name="name" label="Template name" maxLength={160} value={value.name} onChange={(next) => set('name', next)} required /><TextField name="key" label="Stable key" maxLength={64} pattern="[a-z][a-z0-9_-]{0,63}" value={value.key} onChange={(next) => set('key', next)} required /><SelectField name="kind" label="Service / configuration type" value={value.kind} onChange={(next) => set('kind', next)} options={['gift_box', 'laser_engraving', 'generic', 'tray']} /><SelectField name="status" label="Approval status" value={value.status} onChange={(next) => set('status', next)} options={['draft', 'approved']} /><CheckField name="active" label="Active" value={value.active} onChange={(next) => set('active', next)} /><SelectField name="pricingMode" label="Pricing mode" value={value.pricingMode} onChange={(next) => set('pricingMode', next)} options={[{ value: 'additive', label: 'Add selections to product price' }, { value: 'delta', label: 'Adjust from original selections' }]} /><MoneyField name="baseAdjustmentPiastres" label="Base adjustment" value={value.baseAdjustmentPiastres} onChange={(next) => set('baseAdjustmentPiastres', next)} allowNegative={value.pricingMode === 'delta'} /></div>
    <h3>Component Groups</h3>{(value.groups || []).map((group, groupIndex) => <fieldset className="commerce-option-group" data-validation-field={`groups.${groupIndex}`} tabIndex={-1} key={groupIndex}><legend>Group {groupIndex + 1}</legend><div className="commerce-editor-grid"><TextField name={`groups.${groupIndex}.key`} label="Group key" maxLength={64} pattern="[a-z][a-z0-9_-]{0,63}" value={group.key} onChange={(next) => changeGroup(groupIndex, 'key', next)} required /><TextField name={`groups.${groupIndex}.label`} label="Group label" maxLength={120} value={group.label} onChange={(next) => changeGroup(groupIndex, 'label', next)} required /><TextField name={`groups.${groupIndex}.minChoices`} label="Minimum choices" type="number" min="0" max="50" value={group.minChoices} onChange={(next) => changeGroup(groupIndex, 'minChoices', next)} /><TextField name={`groups.${groupIndex}.maxChoices`} label="Maximum choices" type="number" min="1" max="50" value={group.maxChoices} onChange={(next) => changeGroup(groupIndex, 'maxChoices', next)} /></div><div className="commerce-editor-grid" data-validation-field={`groups.${groupIndex}.allowedActions`} tabIndex={-1} role="group" aria-label={`Allowed actions for group ${groupIndex + 1}`}>{['add', 'remove', 'replace'].map((action) => <CheckField name={`groups.${groupIndex}.allowedActions`} key={action} label={`Allow ${action}`} value={(group.allowedActions || []).includes(action)} onChange={(checked) => changeGroup(groupIndex, 'allowedActions', checked ? [...(group.allowedActions || []), action] : (group.allowedActions || []).filter((entry) => entry !== action))} />)}</div>
      <div data-validation-field={`groups.${groupIndex}.options`} tabIndex={-1}>{group.options.map((option, optionIndex) => <div className="commerce-editor-row" key={optionIndex}><div className="commerce-editor-grid"><TextField name={`groups.${groupIndex}.options.${optionIndex}.key`} label="Option key" maxLength={64} pattern="[a-z][a-z0-9_-]{0,63}" value={option.key} onChange={(next) => changeOption(groupIndex, optionIndex, 'key', next)} required /><TextField name={`groups.${groupIndex}.options.${optionIndex}.label`} label="Option label" maxLength={120} value={option.label} onChange={(next) => changeOption(groupIndex, optionIndex, 'label', next)} required /><CheckField name={`groups.${groupIndex}.options.${optionIndex}.active`} label="Active" value={option.active} onChange={(next) => changeOption(groupIndex, optionIndex, 'active', next)} /></div><ComponentPicker name={`groups.${groupIndex}.options.${optionIndex}.componentId`} value={option.componentId} onChange={(next) => changeOption(groupIndex, optionIndex, 'componentId', next)} /><div className="commerce-editor-grid"><MoneyField name={`groups.${groupIndex}.options.${optionIndex}.priceAdjustmentPiastres`} label="Additional price adjustment" value={option.priceAdjustmentPiastres} onChange={(next) => changeOption(groupIndex, optionIndex, 'priceAdjustmentPiastres', next)} allowNegative={value.pricingMode === 'delta'} /><TextField name={`groups.${groupIndex}.options.${optionIndex}.minQuantity`} label="Minimum quantity" type="number" min="1" max="20" value={option.minQuantity} onChange={(next) => changeOption(groupIndex, optionIndex, 'minQuantity', next)} /><TextField name={`groups.${groupIndex}.options.${optionIndex}.maxQuantity`} label="Maximum quantity" type="number" min="1" max="20" value={option.maxQuantity} onChange={(next) => changeOption(groupIndex, optionIndex, 'maxQuantity', next)} /><TextField name={`groups.${groupIndex}.options.${optionIndex}.defaultQuantity`} label="Original quantity" type="number" min="0" max="20" value={option.defaultQuantity} onChange={(next) => changeOption(groupIndex, optionIndex, 'defaultQuantity', next)} /></div><button className="commerce-link-button" type="button" onClick={() => changeGroup(groupIndex, 'options', group.options.filter((_, position) => position !== optionIndex))}>Remove option</button></div>)}</div>
      <div className="commerce-editor-actions"><button className="button button-secondary" type="button" onClick={() => changeGroup(groupIndex, 'options', [...group.options, { key: '', label: '', componentId: null, active: true, priceAdjustmentPiastres: 0, minQuantity: 1, maxQuantity: 1, defaultQuantity: 0 }])}>Add component option</button><button className="commerce-link-button" type="button" onClick={() => set('groups', value.groups.filter((_, position) => position !== groupIndex))}>Remove group</button></div></fieldset>)}
    <button className="button button-secondary" type="button" onClick={() => set('groups', [...(value.groups || []), { key: '', label: '', minChoices: 0, maxChoices: 1, allowedActions: ['add', 'remove', 'replace'], options: [] }])}>Add component group</button>
    <FieldDefinitions fields={value.fields || []} onChange={(next) => set('fields', next)} />
    {value.kind === 'laser_engraving' && <fieldset className="commerce-option-group"><legend>Laser Engraving Settings</legend><p>Configure only products, materials and engraving options that the business has explicitly approved.</p><div className="commerce-editor-grid"><CheckField name="engraving.textRequired" label="Engraving text required" value={engraving.textRequired} onChange={(next) => setEngraving('textRequired', next)} /><TextField name="engraving.maxChars" label="Maximum characters" type="number" min="1" max="500" value={engraving.maxChars} onChange={(next) => setEngraving('maxChars', next)} /><TextField name="engraving.allowedTextLines" label="Allowed text lines" type="number" min="1" max="5" value={engraving.allowedTextLines || 1} onChange={(next) => setEngraving('allowedTextLines', next)} /><TextField name="engraving.maxCharsPerLine" label="Maximum characters per line" type="number" min="1" max="500" value={engraving.maxCharsPerLine || engraving.maxChars} onChange={(next) => setEngraving('maxCharsPerLine', next)} /><MoneyField name="engraving.baseAdjustmentPiastres" label="Engraving base charge" value={engraving.baseAdjustmentPiastres} onChange={(next) => setEngraving('baseAdjustmentPiastres', next)} /><CheckField name="engraving.artworkAllowed" label="Artwork allowed" value={engraving.artworkAllowed} onChange={(next) => setEngraving('artworkAllowed', next)} /><CheckField name="engraving.artworkRequired" label="Artwork required" value={engraving.artworkRequired} onChange={(next) => setEngraving('artworkRequired', next)} /></div>{engraving.artworkAllowed && <div className="commerce-editor-grid"><TextField name="engraving.artworkMaxFiles" label="Maximum artwork files" type="number" min="1" max="5" value={engraving.artworkMaxFiles || 1} onChange={(next) => setEngraving('artworkMaxFiles', next)} /><TextField name="engraving.artworkMaxBytes" label="Maximum artwork size (bytes; 1048576 = 1 MB)" type="number" min="1" max="10485760" value={engraving.artworkMaxBytes ?? 8 * 1024 * 1024} onChange={(next) => setEngraving('artworkMaxBytes', next)} /></div>}{['materials', 'fonts', 'placements'].map((key) => <EngravingOptions key={key} name={key[0].toUpperCase() + key.slice(1)} options={engraving[key] || []} onChange={(next) => setEngraving(key, next)} />)}</fieldset>}
  </>;
}

export function ComponentEditor({ value, onChange, creating = !value._id && !value.id }) {
  const [parentSlug, setParentSlug] = useState('');
  const set = (key, next) => {
    const updated = { ...value, [key]: next };
    if (['pricePiastres', 'compareAtPiastres'].includes(key) && value[key] !== next) {
      updated.priceApproved = false;
      updated.configurationApproved = false;
    }
    if (['enabledForCustomization', 'reviewRequired', 'name', 'description'].includes(key) && value[key] !== next) updated.configurationApproved = false;
    if (key === 'inventory' && ['mode', 'quantity', 'available'].some((field) => value.inventory?.[field] !== next[field])) {
      updated.inventory = { ...next, approved: false };
      updated.configurationApproved = false;
    }
    onChange(updated);
  };
  const inventory = value.inventory || { mode: 'tracked', quantity: 10, approved: false, available: true };
  const setInventory = (key, next) => set('inventory', { ...inventory, [key]: next });
  return <><div className="commerce-editor-grid"><TextField name="name" label="Component name" value={value.name} onChange={(next) => set('name', next)} required /><MoneyField name="pricePiastres" label="Component price" value={value.pricePiastres} onChange={(next) => set('pricePiastres', next)} /><MoneyField name="compareAtPiastres" label="Compare-at price" value={value.compareAtPiastres} onChange={(next) => set('compareAtPiastres', next)} /><CheckField name="priceApproved" label="Price approved" value={value.priceApproved} onChange={(next) => set('priceApproved', next)} /><CheckField name="enabledForCustomization" label="Enabled for customization" value={value.enabledForCustomization} onChange={(next) => set('enabledForCustomization', next)} /><CheckField name="configurationApproved" label="Configuration approved" value={value.configurationApproved} onChange={(next) => set('configurationApproved', next)} /><CheckField name="reviewRequired" label="Catalog review resolved" value={value.reviewRequired === false} onChange={(resolved) => set('reviewRequired', !resolved)} /></div>{value.reviewReasons?.length > 0 && <ul>{value.reviewReasons.map((reason) => <li key={reason}>{reason}</li>)}</ul>}<label className="commerce-field">Merchant review notes<textarea name="merchantReviewNotes" value={value.merchantReviewNotes || ''} maxLength={2000} rows={3} onChange={(event) => set('merchantReviewNotes', event.target.value)} /></label><label className="commerce-field">Description<textarea name="description" value={value.description || ''} rows={3} onChange={(event) => set('description', event.target.value)} /></label>
    {creating && <fieldset className="commerce-option-group"><legend>New Component Catalog References</legend><TextField name="slug" label="Unique slug" value={value.slug} onChange={(next) => set('slug', next)} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /><TextField name="sku" label="SKU (optional)" value={value.sku} onChange={(next) => set('sku', next)} /><CategoryPicker name="categoryId" value={value.categoryId} onChange={(categoryId, category) => { onChange({ ...value, categoryId, subcategoryId: null }); setParentSlug(category?.slug || ''); }} /><CategoryPicker name="subcategoryId" value={value.subcategoryId} label="Subcategory (optional)" required={false} parent={parentSlug || null} onChange={(subcategoryId) => set('subcategoryId', subcategoryId)} /><label className="commerce-field">Existing image references (one per line)<textarea name="galleryKeys" required rows={4} value={(value.galleryKeys || []).join('\n')} onChange={(event) => { const galleryKeys = event.target.value.split('\n').map((entry) => entry.trim()).filter(Boolean); onChange({ ...value, galleryKeys, mainImageKey: galleryKeys.includes(value.mainImageKey) ? value.mainImageKey : galleryKeys[0] || '' }); }} /></label><label className="commerce-field">Main image<select name="mainImageKey" required value={value.mainImageKey || ''} onChange={(event) => onChange({ ...value, mainImageKey: event.target.value, galleryKeys: [event.target.value, ...value.galleryKeys.filter((key) => key !== event.target.value)] })}><option value="">Select main image</option>{(value.galleryKeys || []).map((key) => <option key={key} value={key}>{key}</option>)}</select></label><p className="commerce-muted">Use approved relative object references. This form does not upload images or expose filesystem paths publicly.</p></fieldset>}
    <fieldset className="commerce-option-group"><legend>Inventory</legend><CheckField name="inventory.mode" label="No Inventory Tracking / Made by Request" value={inventory.mode === 'made_to_order'} onChange={(checked) => set('inventory', { ...inventory, mode: checked ? 'made_to_order' : 'tracked', quantity: checked ? null : 10, approved: false })} />{inventory.mode === 'tracked' && <TextField name="inventory.quantity" label="Stock quantity" type="number" min="0" max="1000000" value={inventory.quantity} onChange={(next) => setInventory('quantity', next)} />}<CheckField name="inventory.approved" label="Inventory approved" value={inventory.approved} onChange={(next) => setInventory('approved', next)} /><CheckField name="inventory.available" label="Available" value={inventory.available} onChange={(next) => setInventory('available', next)} /></fieldset></>;
}

export function BundleEditor({ value, onChange }) {
  const set = (key, next) => onChange({ ...value, [key]: next });
  const changeItem = (index, key, next) => set('items', value.items.map((item, position) => position === index ? { ...item, [key]: next } : item));
  return <>
    <div className="commerce-editor-grid">
      <TextField name="name" label="Bundle name" value={value.name} onChange={(next) => set('name', next)} required />
      <CheckField name="active" label="Active" value={value.active} onChange={(next) => set('active', next)} />
      <CheckField name="published" label="Publish eligible bundle on homepage" value={value.published} onChange={(next) => set('published', next)} />
      <SelectField name="discountKind" label="Discount type" value={value.discountKind} onChange={(next) => set('discountKind', next)} options={['fixed', 'percentage']} />
      {value.discountKind === 'percentage' ? <MoneyField name="discountValue" label="Discount percentage" unit="%" maximum={10000} minimum={1} value={value.discountValue} onChange={(next) => set('discountValue', next)} required /> : <MoneyField name="discountValue" label="Fixed discount" value={value.discountValue} onChange={(next) => set('discountValue', next)} required />}
      <TextField name="maxApplications" label="Maximum applications per order" type="number" min="1" max="100" value={value.maxApplications} onChange={(next) => set('maxApplications', next)} />
      <TextField name="priority" label="Priority" type="number" min="0" max="10000" value={value.priority} onChange={(next) => set('priority', next)} />
      <BusinessDateTimeField name="startsAt" label="Starts at (optional)" value={value.startsAt} onChange={(next) => set('startsAt', next)} />
      <BusinessDateTimeField name="endsAt" label="Ends at (optional)" value={value.endsAt} onChange={(next) => set('endsAt', next)} />
    </div>
    <label className="commerce-field">Owner-approved bundle description<textarea name="description" maxLength={2000} rows={3} value={value.description || ''} onChange={(event) => set('description', event.target.value)} /></label>
    <p className="commerce-muted">Homepage publication is separate from the active discount rule. Public bundles require currently approved and available products, configured variants and active categories.</p>
    <h3>Required Products</h3>
    {value.items.map((item, index) => <div key={index} className="commerce-editor-row"><ProductPicker name={`items.${index}.productId`} value={item.productId} onChange={(next) => changeItem(index, 'productId', next)} /><TextField name={`items.${index}.variantKey`} label="Variant key (optional)" value={item.variantKey} onChange={(next) => changeItem(index, 'variantKey', next || null)} /><TextField name={`items.${index}.quantity`} label="Required quantity" type="number" min="1" max="20" value={item.quantity} onChange={(next) => changeItem(index, 'quantity', next)} /><button type="button" className="commerce-link-button" onClick={() => set('items', value.items.filter((_, position) => position !== index))}>Remove product</button></div>)}
    <button type="button" className="button button-secondary" disabled={value.items.length >= 20} onClick={() => set('items', [...value.items, { productId: '', variantKey: null, quantity: 1 }])}>Add bundle product</button>
  </>;
}

export function DiscountEditor({ value, onChange }) {
  const set = (key, next) => onChange({ ...value, [key]: next });
  return <><div className="commerce-editor-grid"><TextField name="name" label="Discount name" value={value.name} onChange={(next) => set('name', next)} required /><TextField name="code" label="Discount code" value={value.code} onChange={(next) => set('code', next.toUpperCase())} required maxLength={40} /><CheckField name="active" label="Active" value={value.active} onChange={(next) => set('active', next)} /><SelectField name="kind" label="Discount type" value={value.kind} onChange={(next) => set('kind', next)} options={['fixed', 'percentage']} />{value.kind === 'percentage' ? <MoneyField name="value" label="Discount percentage" unit="%" maximum={10000} minimum={1} value={value.value} onChange={(next) => set('value', next)} required /> : <MoneyField name="value" label="Fixed discount" value={value.value} onChange={(next) => set('value', next)} required />}<MoneyField name="minimumSubtotalPiastres" label="Minimum subtotal" value={value.minimumSubtotalPiastres} onChange={(next) => set('minimumSubtotalPiastres', next)} /><MoneyField name="maximumDiscountPiastres" label="Maximum discount (optional)" value={value.maximumDiscountPiastres} onChange={(next) => set('maximumDiscountPiastres', next)} /><CheckField name="authenticatedOnly" label="Registered customers only" value={value.authenticatedOnly} onChange={(next) => set('authenticatedOnly', next)} /><CheckField name="stackWithBundles" label="May stack with bundle discounts" value={value.stackWithBundles} onChange={(next) => set('stackWithBundles', next)} /><TextField name="usageLimit" label="Total usage limit (optional)" type="number" min="1" value={value.usageLimit} onChange={(next) => set('usageLimit', next)} /><TextField name="perCustomerLimit" label="Per-customer limit (optional)" type="number" min="1" value={value.perCustomerLimit} onChange={(next) => set('perCustomerLimit', next)} /><BusinessDateTimeField name="startsAt" label="Starts at (optional)" value={value.startsAt} onChange={(next) => set('startsAt', next)} /><BusinessDateTimeField name="endsAt" label="Ends at (optional)" value={value.endsAt} onChange={(next) => set('endsAt', next)} /></div><section><h3>Eligible Products (optional)</h3><p>Leave empty for all otherwise eligible products. Existing category restrictions are preserved.</p>{(value.productIds || []).map((id, index) => <div key={index}><ProductPicker name={`productIds.${index}`} value={id} onChange={(next) => set('productIds', value.productIds.map((entry, position) => position === index ? next : entry))} /><button type="button" className="commerce-link-button" onClick={() => set('productIds', value.productIds.filter((_, position) => position !== index))}>Remove restriction</button></div>)}<button type="button" className="button button-secondary" onClick={() => set('productIds', [...(value.productIds || []), ''])}>Restrict to product</button></section></>;
}
