import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../services/api';
import { adminCommerceGet } from './api';

export function TextField({ label, value, onChange, type = 'text', required = false, ...rest }) {
  return <label className="commerce-field">{label}<input type={type} value={value ?? ''} onChange={(event) => onChange(type === 'number' ? (event.target.value === '' ? null : Number(event.target.value)) : event.target.value)} required={required} {...rest} /></label>;
}
export function MoneyField({ label, value, onChange, required = false, allowNegative = false }) {
  return <label className="commerce-field">{label} (EGP)<input type="number" step="0.01" min={allowNegative ? undefined : 0} required={required} value={Number.isSafeInteger(value) ? value / 100 : ''} onChange={(event) => onChange(event.target.value === '' ? null : Math.round(Number(event.target.value) * 100))} /></label>;
}
export function CheckField({ label, value, onChange }) {
  return <label className="commerce-field"><span><input type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} /> {label}</span></label>;
}
export function SelectField({ label, value, onChange, options, required = false }) {
  return <label className="commerce-field">{label}<select value={value ?? ''} required={required} onChange={(event) => onChange(event.target.value)}>{options.map((entry) => <option value={typeof entry === 'string' ? entry : entry.value} key={typeof entry === 'string' ? entry : entry.value}>{typeof entry === 'string' ? entry.replaceAll('_', ' ') : entry.label}</option>)}</select></label>;
}

export function ProductPicker({ value, onChange, label = 'Product', allowEmpty = false }) {
  const [search, setSearch] = useState('');
  const [submitted, setSubmitted] = useState('');
  const query = useQuery({ queryKey: ['admin', 'commerce', 'product-picker', submitted], queryFn: async ({ signal }) => (await api.get('/admin/products', { params: { q: submitted || undefined, limit: 20, page: 1 }, signal })).data.data, retry: false, staleTime: 60_000 });
  const products = query.data?.products || [];
  return <div className="commerce-editor-row"><label className="commerce-field">Find {label.toLowerCase()}<input value={search} onChange={(event) => setSearch(event.target.value)} /></label><button className="button button-secondary" type="button" onClick={() => setSubmitted(search.trim())}>Find products</button><label className="commerce-field">{label}<select value={value || ''} required={!allowEmpty} onChange={(event) => onChange(event.target.value)}><option value="">Select product</option>{value && !products.some((product) => (product._id || product.id) === value) && <option value={value}>Selected product ({value})</option>}{products.map((product) => <option key={product._id || product.id} value={product._id || product.id}>{product.name}</option>)}</select></label>{query.isFetching && <small role="status">Loading up to 20 products…</small>}</div>;
}
function ComponentPicker({ value, onChange }) {
  const [search, setSearch] = useState('');
  const [submitted, setSubmitted] = useState('');
  const query = useQuery({ queryKey: ['admin', 'commerce', 'component-picker', submitted], queryFn: ({ signal }) => adminCommerceGet('/components', { search: submitted || undefined, limit: 20, page: 1 }, signal), retry: false, staleTime: 60_000 });
  const components = query.data?.components || [];
  return <div><div className="commerce-inline-form"><label className="commerce-field">Find component<input value={search} onChange={(event) => setSearch(event.target.value)} /></label><button type="button" className="button button-secondary" onClick={() => setSubmitted(search.trim())}>Find</button></div><label className="commerce-field">Component (optional)<select value={value || ''} onChange={(event) => onChange(event.target.value || null)}><option value="">No component — adjustment only</option>{value && !components.some((component) => (component._id || component.id) === value) && <option value={value}>Selected component ({value})</option>}{components.map((component) => <option key={component._id || component.id} value={component._id || component.id}>{component.name}</option>)}</select></label></div>;
}

export function CategoryPicker({ value, onChange, parent = 'root', label = 'Main category', required = true }) {
  const [search, setSearch] = useState('');
  const [submitted, setSubmitted] = useState('');
  const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ['admin', 'commerce', 'category-picker', parent, submitted, page], queryFn: async ({ signal }) => (await api.get('/admin/categories', { params: { parent, search: submitted || undefined, limit: 20, page }, signal })).data.data, enabled: Boolean(parent), retry: false, staleTime: 60_000 });
  const categories = query.data?.categories || [];
  return <div className="commerce-editor-row"><div className="commerce-inline-form"><label className="commerce-field">Find {label.toLowerCase()}<input value={search} onChange={(event) => setSearch(event.target.value)} disabled={!parent} /></label><button type="button" className="button button-secondary" disabled={!parent} onClick={() => { setSubmitted(search.trim()); setPage(1); }}>Find categories</button></div><label className="commerce-field">{label}<select value={value || ''} disabled={!parent} required={required} onChange={(event) => onChange(event.target.value || null, categories.find((category) => category._id === event.target.value))}><option value="">Select category</option>{value && !categories.some((category) => category._id === value) && <option value={value}>Current selected category</option>}{categories.map((category) => <option key={category._id} value={category._id}>{category.name}{category.active ? '' : ' (inactive)'}</option>)}</select></label><nav className="commerce-pagination" aria-label={`${label} pages`}><button type="button" disabled={page <= 1 || query.isFetching} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page}</span><button type="button" disabled={query.isFetching || page >= (query.data?.pagination?.pages || query.data?.pagination?.totalPages || 1)} onClick={() => setPage(page + 1)}>Next</button></nav></div>;
}

export function FieldDefinitions({ fields, onChange, product = false }) {
  const update = (index, key, value) => onChange(fields.map((field, position) => position === index ? { ...field, [key]: value } : field));
  return <section><h3>{product ? 'Purchase Requirements' : 'Personalization Fields'}</h3>{fields.map((field, index) => <div className="commerce-editor-row" key={index}><div className="commerce-editor-grid"><TextField label="Field key" value={field.key} onChange={(value) => update(index, 'key', value)} required pattern="[a-z][a-z0-9_]{0,63}" /><TextField label="Customer-facing label" value={field.label} onChange={(value) => update(index, 'label', value)} required /><SelectField label="Field type" value={field.type} onChange={(value) => update(index, 'type', value)} options={product ? ['short_text', 'long_text', 'select', 'image'] : ['text', 'textarea', 'image']} /><CheckField label="Required" value={field.required} onChange={(value) => update(index, 'required', value)} /></div>
    {field.type === 'image' ? <><div className="commerce-editor-grid"><TextField label="Minimum files" type="number" min="0" max="10" value={field.minFiles} onChange={(value) => update(index, 'minFiles', value)} /><TextField label="Maximum files" type="number" min="1" max="10" value={field.maxFiles} onChange={(value) => update(index, 'maxFiles', value)} /><TextField label="Maximum size per file (MB)" type="number" min="1" max="10" value={(field.maxBytes || 8 * 1024 * 1024) / 1024 / 1024} onChange={(value) => update(index, 'maxBytes', value * 1024 * 1024)} /></div><fieldset className="commerce-option-group"><legend>Accepted formats</legend>{['image/jpeg', 'image/png', 'image/webp'].map((mime) => <CheckField key={mime} label={mime.replace('image/', '').toUpperCase()} value={(field.acceptedMimeTypes || []).includes(mime)} onChange={(checked) => update(index, 'acceptedMimeTypes', checked ? [...(field.acceptedMimeTypes || []), mime] : (field.acceptedMimeTypes || []).filter((value) => value !== mime))} />)}</fieldset></> : <><TextField label="Character limit" type="number" min="1" max={product ? 5000 : 10000} value={field[product ? 'maxLength' : 'maxChars']} onChange={(value) => update(index, product ? 'maxLength' : 'maxChars', value)} />{field.type === 'select' && <label className="commerce-field">Choices (one per line)<textarea value={(field.choices || []).join('\n')} onChange={(event) => update(index, 'choices', event.target.value.split('\n').filter(Boolean))} rows={4} /></label>}</>}
    <button className="commerce-link-button" type="button" onClick={() => onChange(fields.filter((_, position) => position !== index))}>Remove field {index + 1}</button></div>)}<button className="button button-secondary" type="button" onClick={() => onChange([...fields, { key: '', label: '', type: product ? 'short_text' : 'text', required: false, [product ? 'maxLength' : 'maxChars']: 120, minFiles: 0, maxFiles: 1, maxBytes: 8 * 1024 * 1024, acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'] }])}>Add requirement field</button></section>;
}

function EngravingOptions({ name, options, onChange }) {
  const change = (index, key, value) => onChange(options.map((option, position) => position === index ? { ...option, [key]: value } : option));
  return <section><h3>{name}</h3>{options.map((option, index) => <div key={index} className="commerce-editor-row"><div className="commerce-editor-grid"><TextField label="Option key" value={option.key} onChange={(value) => change(index, 'key', value)} required /><TextField label="Label" value={option.label} onChange={(value) => change(index, 'label', value)} required /><MoneyField label="Price adjustment" value={option.adjustmentPiastres} onChange={(value) => change(index, 'adjustmentPiastres', value)} /><CheckField label="Available" value={option.active} onChange={(value) => change(index, 'active', value)} /></div><button className="commerce-link-button" type="button" onClick={() => onChange(options.filter((_, position) => position !== index))}>Remove option</button></div>)}<button className="button button-secondary" type="button" onClick={() => onChange([...options, { key: '', label: '', active: true, adjustmentPiastres: 0 }])}>Add {name.toLowerCase()} option</button></section>;
}

export function TemplateEditor({ value, onChange }) {
  const set = (key, next) => onChange({ ...value, [key]: next });
  const changeGroup = (index, key, next) => set('groups', value.groups.map((group, position) => position === index ? { ...group, [key]: next } : group));
  const changeOption = (groupIndex, optionIndex, key, next) => changeGroup(groupIndex, 'options', value.groups[groupIndex].options.map((option, position) => position === optionIndex ? { ...option, [key]: next } : option));
  const engraving = value.engraving || {};
  const setEngraving = (key, next) => set('engraving', { ...engraving, [key]: next });
  return <><div className="commerce-editor-grid"><TextField label="Template name" value={value.name} onChange={(next) => set('name', next)} required /><TextField label="Stable key" value={value.key} onChange={(next) => set('key', next)} required /><SelectField label="Service / configuration type" value={value.kind} onChange={(next) => set('kind', next)} options={['gift_box', 'laser_engraving', 'generic', 'tray']} /><SelectField label="Approval status" value={value.status} onChange={(next) => set('status', next)} options={['draft', 'approved']} /><CheckField label="Active" value={value.active} onChange={(next) => set('active', next)} /><SelectField label="Pricing mode" value={value.pricingMode} onChange={(next) => set('pricingMode', next)} options={[{ value: 'additive', label: 'Add selections to product price' }, { value: 'delta', label: 'Adjust from original selections' }]} /><MoneyField label="Base adjustment" value={value.baseAdjustmentPiastres} onChange={(next) => set('baseAdjustmentPiastres', next)} allowNegative={value.pricingMode === 'delta'} /></div>
    <h3>Component Groups</h3>{(value.groups || []).map((group, groupIndex) => <fieldset className="commerce-option-group" key={groupIndex}><legend>Group {groupIndex + 1}</legend><div className="commerce-editor-grid"><TextField label="Group key" value={group.key} onChange={(next) => changeGroup(groupIndex, 'key', next)} required /><TextField label="Group label" value={group.label} onChange={(next) => changeGroup(groupIndex, 'label', next)} required /><TextField label="Minimum choices" type="number" min="0" max="30" value={group.minChoices} onChange={(next) => changeGroup(groupIndex, 'minChoices', next)} /><TextField label="Maximum choices" type="number" min="1" max="30" value={group.maxChoices} onChange={(next) => changeGroup(groupIndex, 'maxChoices', next)} /></div><div className="commerce-editor-grid">{['add', 'remove', 'replace'].map((action) => <CheckField key={action} label={`Allow ${action}`} value={(group.allowedActions || []).includes(action)} onChange={(checked) => changeGroup(groupIndex, 'allowedActions', checked ? [...(group.allowedActions || []), action] : (group.allowedActions || []).filter((entry) => entry !== action))} />)}</div>
      {group.options.map((option, optionIndex) => <div className="commerce-editor-row" key={optionIndex}><div className="commerce-editor-grid"><TextField label="Option key" value={option.key} onChange={(next) => changeOption(groupIndex, optionIndex, 'key', next)} required /><TextField label="Option label" value={option.label} onChange={(next) => changeOption(groupIndex, optionIndex, 'label', next)} required /><CheckField label="Active" value={option.active} onChange={(next) => changeOption(groupIndex, optionIndex, 'active', next)} /><CheckField label="Available" value={option.available} onChange={(next) => changeOption(groupIndex, optionIndex, 'available', next)} /></div><ComponentPicker value={option.componentId} onChange={(next) => changeOption(groupIndex, optionIndex, 'componentId', next)} /><div className="commerce-editor-grid"><MoneyField label="Additional price adjustment" value={option.priceAdjustmentPiastres} onChange={(next) => changeOption(groupIndex, optionIndex, 'priceAdjustmentPiastres', next)} allowNegative={value.pricingMode === 'delta'} /><TextField label="Minimum quantity" type="number" min="1" max="99" value={option.minQuantity} onChange={(next) => changeOption(groupIndex, optionIndex, 'minQuantity', next)} /><TextField label="Maximum quantity" type="number" min="1" max="99" value={option.maxQuantity} onChange={(next) => changeOption(groupIndex, optionIndex, 'maxQuantity', next)} /><TextField label="Original quantity" type="number" min="0" max="99" value={option.defaultQuantity} onChange={(next) => changeOption(groupIndex, optionIndex, 'defaultQuantity', next)} /></div><button className="commerce-link-button" type="button" onClick={() => changeGroup(groupIndex, 'options', group.options.filter((_, position) => position !== optionIndex))}>Remove option</button></div>)}
      <div className="commerce-editor-actions"><button className="button button-secondary" type="button" onClick={() => changeGroup(groupIndex, 'options', [...group.options, { key: '', label: '', componentId: null, active: true, available: true, priceAdjustmentPiastres: 0, minQuantity: 1, maxQuantity: 1, defaultQuantity: 0 }])}>Add component option</button><button className="commerce-link-button" type="button" onClick={() => set('groups', value.groups.filter((_, position) => position !== groupIndex))}>Remove group</button></div></fieldset>)}
    <button className="button button-secondary" type="button" onClick={() => set('groups', [...(value.groups || []), { key: '', label: '', minChoices: 0, maxChoices: 1, allowedActions: ['add', 'remove', 'replace'], options: [] }])}>Add component group</button>
    <FieldDefinitions fields={value.fields || []} onChange={(next) => set('fields', next)} />
    {value.kind === 'laser_engraving' && <fieldset className="commerce-option-group"><legend>Laser Engraving Settings</legend><p>Configure only products, materials and engraving options that the business has explicitly approved.</p><div className="commerce-editor-grid"><CheckField label="Engraving text required" value={engraving.textRequired} onChange={(next) => setEngraving('textRequired', next)} /><TextField label="Maximum characters" type="number" min="1" max="1000" value={engraving.maxChars} onChange={(next) => setEngraving('maxChars', next)} /><TextField label="Allowed text lines" type="number" min="1" max="5" value={engraving.allowedTextLines || 1} onChange={(next) => setEngraving('allowedTextLines', next)} /><TextField label="Maximum characters per line" type="number" min="1" max="500" value={engraving.maxCharsPerLine || engraving.maxChars} onChange={(next) => setEngraving('maxCharsPerLine', next)} /><MoneyField label="Engraving base charge" value={engraving.baseAdjustmentPiastres} onChange={(next) => setEngraving('baseAdjustmentPiastres', next)} /><CheckField label="Artwork allowed" value={engraving.artworkAllowed} onChange={(next) => setEngraving('artworkAllowed', next)} /><CheckField label="Artwork required" value={engraving.artworkRequired} onChange={(next) => setEngraving('artworkRequired', next)} /></div>{engraving.artworkAllowed && <div className="commerce-editor-grid"><TextField label="Maximum artwork files" type="number" min="1" max="10" value={engraving.artworkMaxFiles || 1} onChange={(next) => setEngraving('artworkMaxFiles', next)} /><TextField label="Maximum artwork size (MB)" type="number" min="1" max="10" value={(engraving.artworkMaxBytes || 8 * 1024 * 1024) / 1024 / 1024} onChange={(next) => setEngraving('artworkMaxBytes', next * 1024 * 1024)} /></div>}{['materials', 'fonts', 'placements'].map((key) => <EngravingOptions key={key} name={key[0].toUpperCase() + key.slice(1)} options={engraving[key] || []} onChange={(next) => setEngraving(key, next)} />)}</fieldset>}
  </>;
}

export function ComponentEditor({ value, onChange, creating = !value._id && !value.id }) {
  const [parentSlug, setParentSlug] = useState('');
  const set = (key, next) => {
    const updated = { ...value, [key]: next };
    if (['pricePiastres', 'compareAtPiastres'].includes(key) && value[key] !== next) {
      updated.priceApproved = false;
      updated.configurationApproved = false;
    }
    if (['enabledForCustomization', 'reviewRequired', 'name', 'description'].includes(key) && value[key] !== next) updated.configurationApproved = false;
    if (key === 'inventory' && ['mode', 'quantity', 'available'].some((field) => value.inventory?.[field] !== next[field])) {
      updated.inventory = { ...next, approved: false };
      updated.configurationApproved = false;
    }
    onChange(updated);
  };
  const inventory = value.inventory || { mode: 'tracked', quantity: 10, approved: false, available: true };
  const setInventory = (key, next) => set('inventory', { ...inventory, [key]: next });
  return <><div className="commerce-editor-grid"><TextField label="Component name" value={value.name} onChange={(next) => set('name', next)} required /><MoneyField label="Component price" value={value.pricePiastres} onChange={(next) => set('pricePiastres', next)} /><MoneyField label="Compare-at price" value={value.compareAtPiastres} onChange={(next) => set('compareAtPiastres', next)} /><CheckField label="Price approved" value={value.priceApproved} onChange={(next) => set('priceApproved', next)} /><CheckField label="Enabled for customization" value={value.enabledForCustomization} onChange={(next) => set('enabledForCustomization', next)} /><CheckField label="Configuration approved" value={value.configurationApproved} onChange={(next) => set('configurationApproved', next)} /><CheckField label="Catalog review resolved" value={value.reviewRequired === false} onChange={(resolved) => set('reviewRequired', !resolved)} /></div>{value.reviewReasons?.length > 0 && <ul>{value.reviewReasons.map((reason) => <li key={reason}>{reason}</li>)}</ul>}<label className="commerce-field">Merchant review notes<textarea value={value.merchantReviewNotes || ''} maxLength={2000} rows={3} onChange={(event) => set('merchantReviewNotes', event.target.value)} /></label><label className="commerce-field">Description<textarea value={value.description || ''} rows={3} onChange={(event) => set('description', event.target.value)} /></label>
    {creating && <fieldset className="commerce-option-group"><legend>New Component Catalog References</legend><TextField label="Unique slug" value={value.slug} onChange={(next) => set('slug', next)} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /><TextField label="SKU (optional)" value={value.sku} onChange={(next) => set('sku', next)} /><CategoryPicker value={value.categoryId} onChange={(categoryId, category) => { onChange({ ...value, categoryId, subcategoryId: null }); setParentSlug(category?.slug || ''); }} /><CategoryPicker value={value.subcategoryId} label="Subcategory (optional)" required={false} parent={parentSlug || null} onChange={(subcategoryId) => set('subcategoryId', subcategoryId)} /><label className="commerce-field">Existing image references (one per line)<textarea required rows={4} value={(value.galleryKeys || []).join('\n')} onChange={(event) => { const galleryKeys = event.target.value.split('\n').map((entry) => entry.trim()).filter(Boolean); onChange({ ...value, galleryKeys, mainImageKey: galleryKeys.includes(value.mainImageKey) ? value.mainImageKey : galleryKeys[0] || '' }); }} /></label><label className="commerce-field">Main image<select required value={value.mainImageKey || ''} onChange={(event) => onChange({ ...value, mainImageKey: event.target.value, galleryKeys: [event.target.value, ...value.galleryKeys.filter((key) => key !== event.target.value)] })}><option value="">Select main image</option>{(value.galleryKeys || []).map((key) => <option key={key} value={key}>{key}</option>)}</select></label><p className="commerce-muted">Use approved relative object references. This form does not upload images or expose filesystem paths publicly.</p></fieldset>}
    <fieldset className="commerce-option-group"><legend>Inventory</legend><CheckField label="No Inventory Tracking / Made by Request" value={inventory.mode === 'made_to_order'} onChange={(checked) => set('inventory', { ...inventory, mode: checked ? 'made_to_order' : 'tracked', quantity: checked ? null : 10, approved: false })} />{inventory.mode === 'tracked' && <TextField label="Stock quantity" type="number" min="0" max="1000000" value={inventory.quantity} onChange={(next) => setInventory('quantity', next)} />}<CheckField label="Inventory approved" value={inventory.approved} onChange={(next) => setInventory('approved', next)} /><CheckField label="Available" value={inventory.available} onChange={(next) => setInventory('available', next)} /></fieldset></>;
}

export function BundleEditor({ value, onChange }) {
  const set = (key, next) => onChange({ ...value, [key]: next });
  const changeItem = (index, key, next) => set('items', value.items.map((item, position) => position === index ? { ...item, [key]: next } : item));
  return <>
    <div className="commerce-editor-grid">
      <TextField label="Bundle name" value={value.name} onChange={(next) => set('name', next)} required />
      <CheckField label="Active" value={value.active} onChange={(next) => set('active', next)} />
      <CheckField label="Publish eligible bundle on homepage" value={value.published} onChange={(next) => set('published', next)} />
      <SelectField label="Discount type" value={value.discountKind} onChange={(next) => set('discountKind', next)} options={['fixed', 'percentage']} />
      {value.discountKind === 'percentage' ? <TextField label="Discount percentage" type="number" min="0.01" max="100" step="0.01" value={(value.discountValue || 0) / 100} onChange={(next) => set('discountValue', Math.round(next * 100))} required /> : <MoneyField label="Fixed discount" value={value.discountValue} onChange={(next) => set('discountValue', next)} required />}
      <TextField label="Maximum applications per order" type="number" min="1" max="100" value={value.maxApplications} onChange={(next) => set('maxApplications', next)} />
      <TextField label="Priority" type="number" min="0" max="10000" value={value.priority} onChange={(next) => set('priority', next)} />
      <TextField label="Starts at (optional)" type="datetime-local" value={value.startsAt ? value.startsAt.slice(0, 16) : ''} onChange={(next) => set('startsAt', next ? new Date(next).toISOString() : null)} />
      <TextField label="Ends at (optional)" type="datetime-local" value={value.endsAt ? value.endsAt.slice(0, 16) : ''} onChange={(next) => set('endsAt', next ? new Date(next).toISOString() : null)} />
    </div>
    <label className="commerce-field">Owner-approved bundle description<textarea maxLength={2000} rows={3} value={value.description || ''} onChange={(event) => set('description', event.target.value)} /></label>
    <p className="commerce-muted">Homepage publication is separate from the active discount rule. Public bundles require currently approved and available products, configured variants and active categories.</p>
    <h3>Required Products</h3>
    {value.items.map((item, index) => <div key={index} className="commerce-editor-row"><ProductPicker value={item.productId} onChange={(next) => changeItem(index, 'productId', next)} /><TextField label="Variant key (optional)" value={item.variantKey} onChange={(next) => changeItem(index, 'variantKey', next || null)} /><TextField label="Required quantity" type="number" min="1" max="20" value={item.quantity} onChange={(next) => changeItem(index, 'quantity', next)} /><button type="button" className="commerce-link-button" onClick={() => set('items', value.items.filter((_, position) => position !== index))}>Remove product</button></div>)}
    <button type="button" className="button button-secondary" disabled={value.items.length >= 20} onClick={() => set('items', [...value.items, { productId: '', variantKey: null, quantity: 1 }])}>Add bundle product</button>
  </>;
}

export function DiscountEditor({ value, onChange }) {
  const set = (key, next) => onChange({ ...value, [key]: next });
  return <><div className="commerce-editor-grid"><TextField label="Discount name" value={value.name} onChange={(next) => set('name', next)} required /><TextField label="Discount code" value={value.code} onChange={(next) => set('code', next.toUpperCase())} required maxLength={40} /><CheckField label="Active" value={value.active} onChange={(next) => set('active', next)} /><SelectField label="Discount type" value={value.kind} onChange={(next) => set('kind', next)} options={['fixed', 'percentage']} />{value.kind === 'percentage' ? <TextField label="Discount percentage" type="number" min="0.01" max="100" step="0.01" value={(value.value || 0) / 100} onChange={(next) => set('value', Math.round(next * 100))} required /> : <MoneyField label="Fixed discount" value={value.value} onChange={(next) => set('value', next)} required />}<MoneyField label="Minimum subtotal" value={value.minimumSubtotalPiastres} onChange={(next) => set('minimumSubtotalPiastres', next)} /><MoneyField label="Maximum discount (optional)" value={value.maximumDiscountPiastres} onChange={(next) => set('maximumDiscountPiastres', next)} /><CheckField label="Registered customers only" value={value.authenticatedOnly} onChange={(next) => set('authenticatedOnly', next)} /><CheckField label="May stack with bundle discounts" value={value.stackWithBundles} onChange={(next) => set('stackWithBundles', next)} /><TextField label="Total usage limit (optional)" type="number" min="1" value={value.usageLimit} onChange={(next) => set('usageLimit', next)} /><TextField label="Per-customer limit (optional)" type="number" min="1" value={value.perCustomerLimit} onChange={(next) => set('perCustomerLimit', next)} /><TextField label="Starts at (optional)" type="datetime-local" value={value.startsAt ? value.startsAt.slice(0, 16) : ''} onChange={(next) => set('startsAt', next ? new Date(next).toISOString() : null)} /><TextField label="Ends at (optional)" type="datetime-local" value={value.endsAt ? value.endsAt.slice(0, 16) : ''} onChange={(next) => set('endsAt', next ? new Date(next).toISOString() : null)} /></div><section><h3>Eligible Products (optional)</h3><p>Leave empty for all otherwise eligible products. Existing category restrictions are preserved.</p>{(value.productIds || []).map((id, index) => <div key={index}><ProductPicker value={id} onChange={(next) => set('productIds', value.productIds.map((entry, position) => position === index ? next : entry))} /><button type="button" className="commerce-link-button" onClick={() => set('productIds', value.productIds.filter((_, position) => position !== index))}>Remove restriction</button></div>)}<button type="button" className="button button-secondary" onClick={() => set('productIds', [...(value.productIds || []), ''])}>Restrict to product</button></section></>;
}
